#!/bin/bash

CHANGED_FILES=$(git diff --cached --name-only)

LINT_BACKEND=false
LINT_FRONTEND=false

for file in $CHANGED_FILES; do
  if [[ $file == ui/* ]]; then
    LINT_FRONTEND=true
  else
    LINT_BACKEND=true
  fi
done

if [ "$LINT_BACKEND" = true ]; then
  echo "Linting Backend"
  golangci-lint run ./... || exit 1
fi

if [ "$LINT_FRONTEND" = true ]; then
  cd ui || exit 1
  echo "Linting Frontend"
  pnpm --silent run lint || exit 1
  echo "Typecheck Frontend"
  pnpm --silent run typecheck || exit 1
  cd - >/dev/null || exit 1
fi

echo "Passed"
