// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: climb.sql

package sqlc

import (
	"context"
)

const climbCreate = `-- name: ClimbCreate :one
INSERT INTO climbs (user_id, external_id, climb_day_id, grade, color, hold_color, climb_type, finish_type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type ClimbCreateParams struct {
	UserID     int32
	ExternalID string
	ClimbDayID int32
	Grade      int32
	Color      string
	HoldColor  string
	ClimbType  ClimbType
	FinishType FinishType
}

func (q *Queries) ClimbCreate(ctx context.Context, arg ClimbCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, climbCreate,
		arg.UserID,
		arg.ExternalID,
		arg.ClimbDayID,
		arg.Grade,
		arg.Color,
		arg.HoldColor,
		arg.ClimbType,
		arg.FinishType,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const climbGet = `-- name: ClimbGet :one
SELECT id, user_id, external_id, climb_day_id, grade, color, hold_color, climb_type, finish_type
FROM climbs
WHERE id = $1
`

func (q *Queries) ClimbGet(ctx context.Context, id int32) (Climb, error) {
	row := q.db.QueryRow(ctx, climbGet, id)
	var i Climb
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExternalID,
		&i.ClimbDayID,
		&i.Grade,
		&i.Color,
		&i.HoldColor,
		&i.ClimbType,
		&i.FinishType,
	)
	return i, err
}

const climbGetAllByClimbDay = `-- name: ClimbGetAllByClimbDay :many
SELECT id, user_id, external_id, climb_day_id, grade, color, hold_color, climb_type, finish_type
FROM climbs
WHERE climb_day_id = $1
`

func (q *Queries) ClimbGetAllByClimbDay(ctx context.Context, climbDayID int32) ([]Climb, error) {
	rows, err := q.db.Query(ctx, climbGetAllByClimbDay, climbDayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Climb
	for rows.Next() {
		var i Climb
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExternalID,
			&i.ClimbDayID,
			&i.Grade,
			&i.Color,
			&i.HoldColor,
			&i.ClimbType,
			&i.FinishType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const climbGetByExternal = `-- name: ClimbGetByExternal :one
SELECT id, user_id, external_id, climb_day_id, grade, color, hold_color, climb_type, finish_type
FROM climbs
WHERE external_id = $1
`

func (q *Queries) ClimbGetByExternal(ctx context.Context, externalID string) (Climb, error) {
	row := q.db.QueryRow(ctx, climbGetByExternal, externalID)
	var i Climb
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExternalID,
		&i.ClimbDayID,
		&i.Grade,
		&i.Color,
		&i.HoldColor,
		&i.ClimbType,
		&i.FinishType,
	)
	return i, err
}

const climbUpdate = `-- name: ClimbUpdate :exec
UPDATE climbs
SET grade = $2, color = $3, hold_color = $4, climb_type = $5, finish_type = $6
WHERE id = $1
`

type ClimbUpdateParams struct {
	ID         int32
	Grade      int32
	Color      string
	HoldColor  string
	ClimbType  ClimbType
	FinishType FinishType
}

func (q *Queries) ClimbUpdate(ctx context.Context, arg ClimbUpdateParams) error {
	_, err := q.db.Exec(ctx, climbUpdate,
		arg.ID,
		arg.Grade,
		arg.Color,
		arg.HoldColor,
		arg.ClimbType,
		arg.FinishType,
	)
	return err
}
