// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: climb_gym.sql

package sqlc

import (
	"context"
)

const climbGymCreate = `-- name: ClimbGymCreate :one
INSERT INTO climb_gyms (user_id, external_id, name, icon_path)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type ClimbGymCreateParams struct {
	UserID     int32
	ExternalID string
	Name       string
	IconPath   string
}

func (q *Queries) ClimbGymCreate(ctx context.Context, arg ClimbGymCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, climbGymCreate,
		arg.UserID,
		arg.ExternalID,
		arg.Name,
		arg.IconPath,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const climbGymGet = `-- name: ClimbGymGet :one
SELECT id, user_id, external_id, name, icon_path
FROM climb_gyms
WHERE id = $1
`

func (q *Queries) ClimbGymGet(ctx context.Context, id int32) (ClimbGym, error) {
	row := q.db.QueryRow(ctx, climbGymGet, id)
	var i ClimbGym
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExternalID,
		&i.Name,
		&i.IconPath,
	)
	return i, err
}

const climbGymGetByExternal = `-- name: ClimbGymGetByExternal :one
SELECT id, user_id, external_id, name, icon_path
FROM climb_gyms
WHERE external_id = $1
`

func (q *Queries) ClimbGymGetByExternal(ctx context.Context, externalID string) (ClimbGym, error) {
	row := q.db.QueryRow(ctx, climbGymGetByExternal, externalID)
	var i ClimbGym
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExternalID,
		&i.Name,
		&i.IconPath,
	)
	return i, err
}

const climbGymGetByExternalIds = `-- name: ClimbGymGetByExternalIds :many
SELECT id, user_id, external_id, name, icon_path
FROM climb_gyms
WHERE external_id = ANY($1::int[])
`

func (q *Queries) ClimbGymGetByExternalIds(ctx context.Context, dollar_1 []int32) ([]ClimbGym, error) {
	rows, err := q.db.Query(ctx, climbGymGetByExternalIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClimbGym
	for rows.Next() {
		var i ClimbGym
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExternalID,
			&i.Name,
			&i.IconPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const climbGymUpdate = `-- name: ClimbGymUpdate :exec
UPDATE climb_gyms
SET name = $2, icon_path = $3
WHERE id = $1
`

type ClimbGymUpdateParams struct {
	ID       int32
	Name     string
	IconPath string
}

func (q *Queries) ClimbGymUpdate(ctx context.Context, arg ClimbGymUpdateParams) error {
	_, err := q.db.Exec(ctx, climbGymUpdate, arg.ID, arg.Name, arg.IconPath)
	return err
}
