// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: climb_day.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const climbDayCreate = `-- name: ClimbDayCreate :one
INSERT INTO climb_days (user_id, external_id, gym_id, day)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type ClimbDayCreateParams struct {
	UserID     int32
	ExternalID string
	GymID      int32
	Day        pgtype.Timestamptz
}

func (q *Queries) ClimbDayCreate(ctx context.Context, arg ClimbDayCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, climbDayCreate,
		arg.UserID,
		arg.ExternalID,
		arg.GymID,
		arg.Day,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const climbDayGet = `-- name: ClimbDayGet :one
SELECT id, user_id, external_id, gym_id, day
FROM climb_days
WHERE id = $1
`

func (q *Queries) ClimbDayGet(ctx context.Context, id int32) (ClimbDay, error) {
	row := q.db.QueryRow(ctx, climbDayGet, id)
	var i ClimbDay
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExternalID,
		&i.GymID,
		&i.Day,
	)
	return i, err
}

const climbDayGetAllPopulatedByExternal = `-- name: ClimbDayGetAllPopulatedByExternal :many
SELECT d.id, d.user_id, d.external_id, d.gym_id, d.day, c.id, c.user_id, c.external_id, c.climb_day_id, c.grade, c.color, c.hold_color, c.climb_type, c.finish_type, g.id, g.user_id, g.external_id, g.name, g.icon_path
FROM climb_days d
LEFT  JOIN climbs c ON c.climb_day_id = d.id
LEFT JOIN climb_gyms g ON d.gym_id = g.id
WHERE g.external_id = ANY($1::int[])
`

type ClimbDayGetAllPopulatedByExternalRow struct {
	ClimbDay ClimbDay
	Climb    Climb
	ClimbGym ClimbGym
}

func (q *Queries) ClimbDayGetAllPopulatedByExternal(ctx context.Context, dollar_1 []int32) ([]ClimbDayGetAllPopulatedByExternalRow, error) {
	rows, err := q.db.Query(ctx, climbDayGetAllPopulatedByExternal, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClimbDayGetAllPopulatedByExternalRow
	for rows.Next() {
		var i ClimbDayGetAllPopulatedByExternalRow
		if err := rows.Scan(
			&i.ClimbDay.ID,
			&i.ClimbDay.UserID,
			&i.ClimbDay.ExternalID,
			&i.ClimbDay.GymID,
			&i.ClimbDay.Day,
			&i.Climb.ID,
			&i.Climb.UserID,
			&i.Climb.ExternalID,
			&i.Climb.ClimbDayID,
			&i.Climb.Grade,
			&i.Climb.Color,
			&i.Climb.HoldColor,
			&i.Climb.ClimbType,
			&i.Climb.FinishType,
			&i.ClimbGym.ID,
			&i.ClimbGym.UserID,
			&i.ClimbGym.ExternalID,
			&i.ClimbGym.Name,
			&i.ClimbGym.IconPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const climbDayGetByExternal = `-- name: ClimbDayGetByExternal :one
SELECT id, user_id, external_id, gym_id, day
FROM climb_days
WHERE external_id = $1
`

func (q *Queries) ClimbDayGetByExternal(ctx context.Context, externalID string) (ClimbDay, error) {
	row := q.db.QueryRow(ctx, climbDayGetByExternal, externalID)
	var i ClimbDay
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExternalID,
		&i.GymID,
		&i.Day,
	)
	return i, err
}

const climbDayGetPopulated = `-- name: ClimbDayGetPopulated :many
SELECT d.id, d.user_id, d.external_id, d.gym_id, d.day, c.id, c.user_id, c.external_id, c.climb_day_id, c.grade, c.color, c.hold_color, c.climb_type, c.finish_type, g.id, g.user_id, g.external_id, g.name, g.icon_path
FROM climb_days d
LEFT  JOIN climbs c ON c.climb_day_id = d.id
LEFT JOIN climb_gyms g ON d.gym_id = g.id
WHERE d.id = $1
`

type ClimbDayGetPopulatedRow struct {
	ClimbDay ClimbDay
	Climb    Climb
	ClimbGym ClimbGym
}

func (q *Queries) ClimbDayGetPopulated(ctx context.Context, id int32) ([]ClimbDayGetPopulatedRow, error) {
	rows, err := q.db.Query(ctx, climbDayGetPopulated, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClimbDayGetPopulatedRow
	for rows.Next() {
		var i ClimbDayGetPopulatedRow
		if err := rows.Scan(
			&i.ClimbDay.ID,
			&i.ClimbDay.UserID,
			&i.ClimbDay.ExternalID,
			&i.ClimbDay.GymID,
			&i.ClimbDay.Day,
			&i.Climb.ID,
			&i.Climb.UserID,
			&i.Climb.ExternalID,
			&i.Climb.ClimbDayID,
			&i.Climb.Grade,
			&i.Climb.Color,
			&i.Climb.HoldColor,
			&i.Climb.ClimbType,
			&i.Climb.FinishType,
			&i.ClimbGym.ID,
			&i.ClimbGym.UserID,
			&i.ClimbGym.ExternalID,
			&i.ClimbGym.Name,
			&i.ClimbGym.IconPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const climbDayGetPopulatedByExternal = `-- name: ClimbDayGetPopulatedByExternal :many
SELECT d.id, d.user_id, d.external_id, d.gym_id, d.day, c.id, c.user_id, c.external_id, c.climb_day_id, c.grade, c.color, c.hold_color, c.climb_type, c.finish_type, g.id, g.user_id, g.external_id, g.name, g.icon_path
FROM climb_days d
LEFT  JOIN climbs c ON c.climb_day_id = d.id
LEFT JOIN climb_gyms g ON d.gym_id = g.id
WHERE g.external_id = $1
`

type ClimbDayGetPopulatedByExternalRow struct {
	ClimbDay ClimbDay
	Climb    Climb
	ClimbGym ClimbGym
}

func (q *Queries) ClimbDayGetPopulatedByExternal(ctx context.Context, externalID string) ([]ClimbDayGetPopulatedByExternalRow, error) {
	rows, err := q.db.Query(ctx, climbDayGetPopulatedByExternal, externalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClimbDayGetPopulatedByExternalRow
	for rows.Next() {
		var i ClimbDayGetPopulatedByExternalRow
		if err := rows.Scan(
			&i.ClimbDay.ID,
			&i.ClimbDay.UserID,
			&i.ClimbDay.ExternalID,
			&i.ClimbDay.GymID,
			&i.ClimbDay.Day,
			&i.Climb.ID,
			&i.Climb.UserID,
			&i.Climb.ExternalID,
			&i.Climb.ClimbDayID,
			&i.Climb.Grade,
			&i.Climb.Color,
			&i.Climb.HoldColor,
			&i.Climb.ClimbType,
			&i.Climb.FinishType,
			&i.ClimbGym.ID,
			&i.ClimbGym.UserID,
			&i.ClimbGym.ExternalID,
			&i.ClimbGym.Name,
			&i.ClimbGym.IconPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const climbDayUpdate = `-- name: ClimbDayUpdate :exec
UPDATE climb_days
SET gym_id = $2, day = $3
WHERE id = $1
`

type ClimbDayUpdateParams struct {
	ID    int32
	GymID int32
	Day   pgtype.Timestamptz
}

func (q *Queries) ClimbDayUpdate(ctx context.Context, arg ClimbDayUpdateParams) error {
	_, err := q.db.Exec(ctx, climbDayUpdate, arg.ID, arg.GymID, arg.Day)
	return err
}
