// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: climb_day.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const climbDayCreate = `-- name: ClimbDayCreate :one
INSERT INTO climb_days (user_id, external_id, gym_id, date, source)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type ClimbDayCreateParams struct {
	UserID     int32
	ExternalID string
	GymID      int32
	Date       pgtype.Timestamptz
	Source     ClimbSource
}

func (q *Queries) ClimbDayCreate(ctx context.Context, arg ClimbDayCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, climbDayCreate,
		arg.UserID,
		arg.ExternalID,
		arg.GymID,
		arg.Date,
		arg.Source,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const climbDayDelete = `-- name: ClimbDayDelete :exec
DELETE FROM climb_days
WHERE id = $1
`

func (q *Queries) ClimbDayDelete(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, climbDayDelete, id)
	return err
}

const climbDayGet = `-- name: ClimbDayGet :one
SELECT id, user_id, external_id, gym_id, date, source
FROM climb_days
WHERE id = $1
`

func (q *Queries) ClimbDayGet(ctx context.Context, id int32) (ClimbDay, error) {
	row := q.db.QueryRow(ctx, climbDayGet, id)
	var i ClimbDay
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExternalID,
		&i.GymID,
		&i.Date,
		&i.Source,
	)
	return i, err
}

const climbDayGetAllPopulatedByExternalSource = `-- name: ClimbDayGetAllPopulatedByExternalSource :many
SELECT d.id, d.user_id, d.external_id, d.gym_id, d.date, d.source, c.id, c.user_id, c.external_id, c.climb_day_id, c.grade, c.hold_color, c.climb_type, c.finish_type, c.source, g.id, g.user_id, g.external_id, g.name, g.icon_path, g.source
FROM climb_days d
LEFT  JOIN climbs c ON c.climb_day_id = d.id
LEFT JOIN gyms g ON d.gym_id = g.id
WHERE d.external_id = ANY($1::int[]) AND d.source = $2
ORDER BY d.date ASC
`

type ClimbDayGetAllPopulatedByExternalSourceParams struct {
	Column1 []int32
	Source  ClimbSource
}

type ClimbDayGetAllPopulatedByExternalSourceRow struct {
	ClimbDay ClimbDay
	Climb    Climb
	Gym      Gym
}

func (q *Queries) ClimbDayGetAllPopulatedByExternalSource(ctx context.Context, arg ClimbDayGetAllPopulatedByExternalSourceParams) ([]ClimbDayGetAllPopulatedByExternalSourceRow, error) {
	rows, err := q.db.Query(ctx, climbDayGetAllPopulatedByExternalSource, arg.Column1, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClimbDayGetAllPopulatedByExternalSourceRow
	for rows.Next() {
		var i ClimbDayGetAllPopulatedByExternalSourceRow
		if err := rows.Scan(
			&i.ClimbDay.ID,
			&i.ClimbDay.UserID,
			&i.ClimbDay.ExternalID,
			&i.ClimbDay.GymID,
			&i.ClimbDay.Date,
			&i.ClimbDay.Source,
			&i.Climb.ID,
			&i.Climb.UserID,
			&i.Climb.ExternalID,
			&i.Climb.ClimbDayID,
			&i.Climb.Grade,
			&i.Climb.HoldColor,
			&i.Climb.ClimbType,
			&i.Climb.FinishType,
			&i.Climb.Source,
			&i.Gym.ID,
			&i.Gym.UserID,
			&i.Gym.ExternalID,
			&i.Gym.Name,
			&i.Gym.IconPath,
			&i.Gym.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const climbDayGetAllPopulatedByUser = `-- name: ClimbDayGetAllPopulatedByUser :many
SELECT d.id, d.user_id, d.external_id, d.gym_id, d.date, d.source, c.id, c.user_id, c.external_id, c.climb_day_id, c.grade, c.hold_color, c.climb_type, c.finish_type, c.source, g.id, g.user_id, g.external_id, g.name, g.icon_path, g.source
FROM climb_days d
LEFT  JOIN climbs c ON c.climb_day_id = d.id
LEFT JOIN gyms g ON d.gym_id = g.id
WHERE d.user_id = $1
ORDER BY d.date ASC
`

type ClimbDayGetAllPopulatedByUserRow struct {
	ClimbDay ClimbDay
	Climb    Climb
	Gym      Gym
}

func (q *Queries) ClimbDayGetAllPopulatedByUser(ctx context.Context, userID int32) ([]ClimbDayGetAllPopulatedByUserRow, error) {
	rows, err := q.db.Query(ctx, climbDayGetAllPopulatedByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClimbDayGetAllPopulatedByUserRow
	for rows.Next() {
		var i ClimbDayGetAllPopulatedByUserRow
		if err := rows.Scan(
			&i.ClimbDay.ID,
			&i.ClimbDay.UserID,
			&i.ClimbDay.ExternalID,
			&i.ClimbDay.GymID,
			&i.ClimbDay.Date,
			&i.ClimbDay.Source,
			&i.Climb.ID,
			&i.Climb.UserID,
			&i.Climb.ExternalID,
			&i.Climb.ClimbDayID,
			&i.Climb.Grade,
			&i.Climb.HoldColor,
			&i.Climb.ClimbType,
			&i.Climb.FinishType,
			&i.Climb.Source,
			&i.Gym.ID,
			&i.Gym.UserID,
			&i.Gym.ExternalID,
			&i.Gym.Name,
			&i.Gym.IconPath,
			&i.Gym.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const climbDayGetAllPopulatedFiltered = `-- name: ClimbDayGetAllPopulatedFiltered :many
SELECT d.id, d.user_id, d.external_id, d.gym_id, d.date, d.source, c.id, c.user_id, c.external_id, c.climb_day_id, c.grade, c.hold_color, c.climb_type, c.finish_type, c.source, g.id, g.user_id, g.external_id, g.name, g.icon_path, g.source
FROM climb_days d
LEFT JOIN climbs c ON c.climb_day_id = d.id
LEFT JOIN gyms g ON d.gym_id = g.id
WHERE d.id IN (
  SELECT id FROM climb_days AS cd
  WHERE cd.user_id = $1
  ORDER BY cd.date DESC
  LIMIT $2 OFFSET $3
)
ORDER BY d.date DESC, c.grade DESC
`

type ClimbDayGetAllPopulatedFilteredParams struct {
	UserID int32
	Limit  int32
	Offset int32
}

type ClimbDayGetAllPopulatedFilteredRow struct {
	ClimbDay ClimbDay
	Climb    Climb
	Gym      Gym
}

func (q *Queries) ClimbDayGetAllPopulatedFiltered(ctx context.Context, arg ClimbDayGetAllPopulatedFilteredParams) ([]ClimbDayGetAllPopulatedFilteredRow, error) {
	rows, err := q.db.Query(ctx, climbDayGetAllPopulatedFiltered, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClimbDayGetAllPopulatedFilteredRow
	for rows.Next() {
		var i ClimbDayGetAllPopulatedFilteredRow
		if err := rows.Scan(
			&i.ClimbDay.ID,
			&i.ClimbDay.UserID,
			&i.ClimbDay.ExternalID,
			&i.ClimbDay.GymID,
			&i.ClimbDay.Date,
			&i.ClimbDay.Source,
			&i.Climb.ID,
			&i.Climb.UserID,
			&i.Climb.ExternalID,
			&i.Climb.ClimbDayID,
			&i.Climb.Grade,
			&i.Climb.HoldColor,
			&i.Climb.ClimbType,
			&i.Climb.FinishType,
			&i.Climb.Source,
			&i.Gym.ID,
			&i.Gym.UserID,
			&i.Gym.ExternalID,
			&i.Gym.Name,
			&i.Gym.IconPath,
			&i.Gym.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const climbDayGetByExternalSource = `-- name: ClimbDayGetByExternalSource :one
SELECT id, user_id, external_id, gym_id, date, source
FROM climb_days
WHERE external_id = $1 AND source = $2
`

type ClimbDayGetByExternalSourceParams struct {
	ExternalID string
	Source     ClimbSource
}

func (q *Queries) ClimbDayGetByExternalSource(ctx context.Context, arg ClimbDayGetByExternalSourceParams) (ClimbDay, error) {
	row := q.db.QueryRow(ctx, climbDayGetByExternalSource, arg.ExternalID, arg.Source)
	var i ClimbDay
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExternalID,
		&i.GymID,
		&i.Date,
		&i.Source,
	)
	return i, err
}

const climbDayGetPopulated = `-- name: ClimbDayGetPopulated :many
SELECT d.id, d.user_id, d.external_id, d.gym_id, d.date, d.source, c.id, c.user_id, c.external_id, c.climb_day_id, c.grade, c.hold_color, c.climb_type, c.finish_type, c.source, g.id, g.user_id, g.external_id, g.name, g.icon_path, g.source
FROM climb_days d
LEFT  JOIN climbs c ON c.climb_day_id = d.id
LEFT JOIN gyms g ON d.gym_id = g.id
WHERE d.id = $1
`

type ClimbDayGetPopulatedRow struct {
	ClimbDay ClimbDay
	Climb    Climb
	Gym      Gym
}

func (q *Queries) ClimbDayGetPopulated(ctx context.Context, id int32) ([]ClimbDayGetPopulatedRow, error) {
	rows, err := q.db.Query(ctx, climbDayGetPopulated, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClimbDayGetPopulatedRow
	for rows.Next() {
		var i ClimbDayGetPopulatedRow
		if err := rows.Scan(
			&i.ClimbDay.ID,
			&i.ClimbDay.UserID,
			&i.ClimbDay.ExternalID,
			&i.ClimbDay.GymID,
			&i.ClimbDay.Date,
			&i.ClimbDay.Source,
			&i.Climb.ID,
			&i.Climb.UserID,
			&i.Climb.ExternalID,
			&i.Climb.ClimbDayID,
			&i.Climb.Grade,
			&i.Climb.HoldColor,
			&i.Climb.ClimbType,
			&i.Climb.FinishType,
			&i.Climb.Source,
			&i.Gym.ID,
			&i.Gym.UserID,
			&i.Gym.ExternalID,
			&i.Gym.Name,
			&i.Gym.IconPath,
			&i.Gym.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const climbDayGetPopulatedByExternalSource = `-- name: ClimbDayGetPopulatedByExternalSource :many
SELECT d.id, d.user_id, d.external_id, d.gym_id, d.date, d.source, c.id, c.user_id, c.external_id, c.climb_day_id, c.grade, c.hold_color, c.climb_type, c.finish_type, c.source, g.id, g.user_id, g.external_id, g.name, g.icon_path, g.source
FROM climb_days d
LEFT  JOIN climbs c ON c.climb_day_id = d.id
LEFT JOIN gyms g ON d.gym_id = g.id
WHERE d.external_id = $1 AND d.source = $2
`

type ClimbDayGetPopulatedByExternalSourceParams struct {
	ExternalID string
	Source     ClimbSource
}

type ClimbDayGetPopulatedByExternalSourceRow struct {
	ClimbDay ClimbDay
	Climb    Climb
	Gym      Gym
}

func (q *Queries) ClimbDayGetPopulatedByExternalSource(ctx context.Context, arg ClimbDayGetPopulatedByExternalSourceParams) ([]ClimbDayGetPopulatedByExternalSourceRow, error) {
	rows, err := q.db.Query(ctx, climbDayGetPopulatedByExternalSource, arg.ExternalID, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClimbDayGetPopulatedByExternalSourceRow
	for rows.Next() {
		var i ClimbDayGetPopulatedByExternalSourceRow
		if err := rows.Scan(
			&i.ClimbDay.ID,
			&i.ClimbDay.UserID,
			&i.ClimbDay.ExternalID,
			&i.ClimbDay.GymID,
			&i.ClimbDay.Date,
			&i.ClimbDay.Source,
			&i.Climb.ID,
			&i.Climb.UserID,
			&i.Climb.ExternalID,
			&i.Climb.ClimbDayID,
			&i.Climb.Grade,
			&i.Climb.HoldColor,
			&i.Climb.ClimbType,
			&i.Climb.FinishType,
			&i.Climb.Source,
			&i.Gym.ID,
			&i.Gym.UserID,
			&i.Gym.ExternalID,
			&i.Gym.Name,
			&i.Gym.IconPath,
			&i.Gym.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const climbDayUpdate = `-- name: ClimbDayUpdate :exec
UPDATE climb_days
SET gym_id = $2, date = $3
WHERE id = $1
`

type ClimbDayUpdateParams struct {
	ID    int32
	GymID int32
	Date  pgtype.Timestamptz
}

func (q *Queries) ClimbDayUpdate(ctx context.Context, arg ClimbDayUpdateParams) error {
	_, err := q.db.Exec(ctx, climbDayUpdate, arg.ID, arg.GymID, arg.Date)
	return err
}
