// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: climb_gym.sql

package sqlc

import (
	"context"
)

const climbGymCreate = `-- name: ClimbGymCreate :one
INSERT INTO climb_gyms (user_id, external_id, name, icon_path, source)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type ClimbGymCreateParams struct {
	UserID     int32
	ExternalID string
	Name       string
	IconPath   string
	Source     ClimbSource
}

func (q *Queries) ClimbGymCreate(ctx context.Context, arg ClimbGymCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, climbGymCreate,
		arg.UserID,
		arg.ExternalID,
		arg.Name,
		arg.IconPath,
		arg.Source,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const climbGymGet = `-- name: ClimbGymGet :one
SELECT id, user_id, external_id, name, icon_path, source
FROM climb_gyms
WHERE id = $1
`

func (q *Queries) ClimbGymGet(ctx context.Context, id int32) (ClimbGym, error) {
	row := q.db.QueryRow(ctx, climbGymGet, id)
	var i ClimbGym
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExternalID,
		&i.Name,
		&i.IconPath,
		&i.Source,
	)
	return i, err
}

const climbGymGetAllByExternalSource = `-- name: ClimbGymGetAllByExternalSource :many
SELECT id, user_id, external_id, name, icon_path, source
FROM climb_gyms
WHERE external_id = ANY($1::int[]) AND source = $2
`

type ClimbGymGetAllByExternalSourceParams struct {
	Column1 []int32
	Source  ClimbSource
}

func (q *Queries) ClimbGymGetAllByExternalSource(ctx context.Context, arg ClimbGymGetAllByExternalSourceParams) ([]ClimbGym, error) {
	rows, err := q.db.Query(ctx, climbGymGetAllByExternalSource, arg.Column1, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClimbGym
	for rows.Next() {
		var i ClimbGym
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExternalID,
			&i.Name,
			&i.IconPath,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const climbGymGetByExternalSource = `-- name: ClimbGymGetByExternalSource :one
SELECT id, user_id, external_id, name, icon_path, source
FROM climb_gyms
WHERE external_id = $1 AND source = $2
`

type ClimbGymGetByExternalSourceParams struct {
	ExternalID string
	Source     ClimbSource
}

func (q *Queries) ClimbGymGetByExternalSource(ctx context.Context, arg ClimbGymGetByExternalSourceParams) (ClimbGym, error) {
	row := q.db.QueryRow(ctx, climbGymGetByExternalSource, arg.ExternalID, arg.Source)
	var i ClimbGym
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExternalID,
		&i.Name,
		&i.IconPath,
		&i.Source,
	)
	return i, err
}

const climbGymUpdate = `-- name: ClimbGymUpdate :exec
UPDATE climb_gyms
SET name = $2, icon_path = $3
WHERE id = $1
`

type ClimbGymUpdateParams struct {
	ID       int32
	Name     string
	IconPath string
}

func (q *Queries) ClimbGymUpdate(ctx context.Context, arg ClimbGymUpdateParams) error {
	_, err := q.db.Exec(ctx, climbGymUpdate, arg.ID, arg.Name, arg.IconPath)
	return err
}
