// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercise.sql

package sqlc

import (
	"context"
)

const exerciseCreate = `-- name: ExerciseCreate :one
INSERT INTO exercises (user_id, name, variants)
VALUES ($1, $2, $3)
RETURNING id
`

type ExerciseCreateParams struct {
	UserID   int32
	Name     string
	Variants []string
}

func (q *Queries) ExerciseCreate(ctx context.Context, arg ExerciseCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, exerciseCreate, arg.UserID, arg.Name, arg.Variants)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const exerciseDelete = `-- name: ExerciseDelete :exec
UPDATE exercises
SET deleted_at = NOW()
WHERE id = $1 AND NOT DELETED
`

func (q *Queries) ExerciseDelete(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, exerciseDelete, id)
	return err
}

const exerciseGet = `-- name: ExerciseGet :one
SELECT id, user_id, name, variants, deleted_at
FROM exercises
WHERE id = $1
`

func (q *Queries) ExerciseGet(ctx context.Context, id int32) (Exercise, error) {
	row := q.db.QueryRow(ctx, exerciseGet, id)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Variants,
		&i.DeletedAt,
	)
	return i, err
}

const exerciseGetAll = `-- name: ExerciseGetAll :many
SELECT id, user_id, name, variants, deleted_at
FROM exercises
WHERE user_id = $1 AND NOT DELETED
ORDER BY name
`

func (q *Queries) ExerciseGetAll(ctx context.Context, userID int32) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, exerciseGetAll, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Variants,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exerciseGetByIDs = `-- name: ExerciseGetByIDs :many
SELECT id, user_id, name, variants, deleted_at
FROM exercises
WHERE id = ANY($1::int[]) AND NOT DELETED
`

func (q *Queries) ExerciseGetByIDs(ctx context.Context, dollar_1 []int32) ([]Exercise, error) {
	rows, err := q.db.Query(ctx, exerciseGetByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Exercise
	for rows.Next() {
		var i Exercise
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Variants,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exerciseUpdate = `-- name: ExerciseUpdate :exec
UPDATE exercises
SET name = $2, variants = $3
WHERE id = $1
`

type ExerciseUpdateParams struct {
	ID       int32
	Name     string
	Variants []string
}

func (q *Queries) ExerciseUpdate(ctx context.Context, arg ExerciseUpdateParams) error {
	_, err := q.db.Exec(ctx, exerciseUpdate, arg.ID, arg.Name, arg.Variants)
	return err
}
