// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercise.sql

package sqlc

import (
	"context"
)

const exerciseCreate = `-- name: ExerciseCreate :one
INSERT INTO exercises (user_id, name)
VALUES ($1, $2)
RETURNING id
`

type ExerciseCreateParams struct {
	UserID int32
	Name   string
}

func (q *Queries) ExerciseCreate(ctx context.Context, arg ExerciseCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, exerciseCreate, arg.UserID, arg.Name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const exerciseDelete = `-- name: ExerciseDelete :exec
UPDATE exercises
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) ExerciseDelete(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, exerciseDelete, id)
	return err
}

const exerciseGet = `-- name: ExerciseGet :many
SELECT e.id, e.user_id, e.name, e.deleted_at, ev.id, ev.exercise_id, ev.variant
FROM exercises e
LEFT JOIN variants_view ev ON e.id = ev.exercise_id
WHERE e.id = $1
`

type ExerciseGetRow struct {
	Exercise     Exercise
	VariantsView VariantsView
}

func (q *Queries) ExerciseGet(ctx context.Context, id int32) ([]ExerciseGetRow, error) {
	rows, err := q.db.Query(ctx, exerciseGet, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExerciseGetRow
	for rows.Next() {
		var i ExerciseGetRow
		if err := rows.Scan(
			&i.Exercise.ID,
			&i.Exercise.UserID,
			&i.Exercise.Name,
			&i.Exercise.DeletedAt,
			&i.VariantsView.ID,
			&i.VariantsView.ExerciseID,
			&i.VariantsView.Variant,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exerciseGetAll = `-- name: ExerciseGetAll :many
SELECT e.id, e.user_id, e.name, e.deleted_at, ev.id, ev.exercise_id, ev.variant
FROM exercises e
LEFT JOIN variants_view ev ON e.id = ev.exercise_id
WHERE e.user_id = $1 AND e.deleted_at IS NULL
ORDER BY e.name, ev.id
`

type ExerciseGetAllRow struct {
	Exercise     Exercise
	VariantsView VariantsView
}

func (q *Queries) ExerciseGetAll(ctx context.Context, userID int32) ([]ExerciseGetAllRow, error) {
	rows, err := q.db.Query(ctx, exerciseGetAll, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExerciseGetAllRow
	for rows.Next() {
		var i ExerciseGetAllRow
		if err := rows.Scan(
			&i.Exercise.ID,
			&i.Exercise.UserID,
			&i.Exercise.Name,
			&i.Exercise.DeletedAt,
			&i.VariantsView.ID,
			&i.VariantsView.ExerciseID,
			&i.VariantsView.Variant,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exerciseGetByIDs = `-- name: ExerciseGetByIDs :many
SELECT e.id, e.user_id, e.name, e.deleted_at, ev.id, ev.exercise_id, ev.variant
FROM exercises e
LEFT JOIN variants_view ev ON e.id = ev.exercise_id
WHERE e.id = ANY($1::int[]) AND e.deleted_at IS NULL
ORDER BY e.name, ev.id
`

type ExerciseGetByIDsRow struct {
	Exercise     Exercise
	VariantsView VariantsView
}

func (q *Queries) ExerciseGetByIDs(ctx context.Context, dollar_1 []int32) ([]ExerciseGetByIDsRow, error) {
	rows, err := q.db.Query(ctx, exerciseGetByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExerciseGetByIDsRow
	for rows.Next() {
		var i ExerciseGetByIDsRow
		if err := rows.Scan(
			&i.Exercise.ID,
			&i.Exercise.UserID,
			&i.Exercise.Name,
			&i.Exercise.DeletedAt,
			&i.VariantsView.ID,
			&i.VariantsView.ExerciseID,
			&i.VariantsView.Variant,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exerciseUpdate = `-- name: ExerciseUpdate :exec
UPDATE exercises
SET name = $2
WHERE id = $1
`

type ExerciseUpdateParams struct {
	ID   int32
	Name string
}

func (q *Queries) ExerciseUpdate(ctx context.Context, arg ExerciseUpdateParams) error {
	_, err := q.db.Exec(ctx, exerciseUpdate, arg.ID, arg.Name)
	return err
}
