// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gym.sql

package sqlc

import (
	"context"
)

const gymCreate = `-- name: GymCreate :one
INSERT INTO gyms (user_id, external_id, name, icon_path, source)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type GymCreateParams struct {
	UserID     int32
	ExternalID string
	Name       string
	IconPath   string
	Source     ClimbSource
}

func (q *Queries) GymCreate(ctx context.Context, arg GymCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, gymCreate,
		arg.UserID,
		arg.ExternalID,
		arg.Name,
		arg.IconPath,
		arg.Source,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const gymGet = `-- name: GymGet :one
SELECT id, user_id, external_id, name, icon_path, source
FROM gyms
WHERE id = $1
`

func (q *Queries) GymGet(ctx context.Context, id int32) (Gym, error) {
	row := q.db.QueryRow(ctx, gymGet, id)
	var i Gym
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExternalID,
		&i.Name,
		&i.IconPath,
		&i.Source,
	)
	return i, err
}

const gymGetAllByExternalSource = `-- name: GymGetAllByExternalSource :many
SELECT id, user_id, external_id, name, icon_path, source
FROM gyms
WHERE external_id = ANY($1::int[]) AND source = $2
`

type GymGetAllByExternalSourceParams struct {
	Column1 []int32
	Source  ClimbSource
}

func (q *Queries) GymGetAllByExternalSource(ctx context.Context, arg GymGetAllByExternalSourceParams) ([]Gym, error) {
	rows, err := q.db.Query(ctx, gymGetAllByExternalSource, arg.Column1, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Gym
	for rows.Next() {
		var i Gym
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExternalID,
			&i.Name,
			&i.IconPath,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const gymGetAllByUser = `-- name: GymGetAllByUser :many
SELECT id, user_id, external_id, name, icon_path, source
FROM gyms
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) GymGetAllByUser(ctx context.Context, userID int32) ([]Gym, error) {
	rows, err := q.db.Query(ctx, gymGetAllByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Gym
	for rows.Next() {
		var i Gym
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExternalID,
			&i.Name,
			&i.IconPath,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const gymGetByExternalSource = `-- name: GymGetByExternalSource :one
SELECT id, user_id, external_id, name, icon_path, source
FROM gyms
WHERE external_id = $1 AND source = $2
`

type GymGetByExternalSourceParams struct {
	ExternalID string
	Source     ClimbSource
}

func (q *Queries) GymGetByExternalSource(ctx context.Context, arg GymGetByExternalSourceParams) (Gym, error) {
	row := q.db.QueryRow(ctx, gymGetByExternalSource, arg.ExternalID, arg.Source)
	var i Gym
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExternalID,
		&i.Name,
		&i.IconPath,
		&i.Source,
	)
	return i, err
}

const gymUpdate = `-- name: GymUpdate :exec
UPDATE gyms
SET name = $2, icon_path = $3
WHERE id = $1
`

type GymUpdateParams struct {
	ID       int32
	Name     string
	IconPath string
}

func (q *Queries) GymUpdate(ctx context.Context, arg GymUpdateParams) error {
	_, err := q.db.Exec(ctx, gymUpdate, arg.ID, arg.Name, arg.IconPath)
	return err
}
