// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ClimbType string

const (
	ClimbTypeBoulder ClimbType = "boulder"
	ClimbTypeLead    ClimbType = "lead"
)

func (e *ClimbType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ClimbType(s)
	case string:
		*e = ClimbType(s)
	default:
		return fmt.Errorf("unsupported scan type for ClimbType: %T", src)
	}
	return nil
}

type NullClimbType struct {
	ClimbType ClimbType
	Valid     bool // Valid is true if ClimbType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullClimbType) Scan(value interface{}) error {
	if value == nil {
		ns.ClimbType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ClimbType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullClimbType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ClimbType), nil
}

type FinishType string

const (
	FinishTypeFlash  FinishType = "flash"
	FinishTypeTop    FinishType = "top"
	FinishTypeRepeat FinishType = "repeat"
)

func (e *FinishType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FinishType(s)
	case string:
		*e = FinishType(s)
	default:
		return fmt.Errorf("unsupported scan type for FinishType: %T", src)
	}
	return nil
}

type NullFinishType struct {
	FinishType FinishType
	Valid      bool // Valid is true if FinishType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFinishType) Scan(value interface{}) error {
	if value == nil {
		ns.FinishType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FinishType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFinishType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FinishType), nil
}

type TaskResult string

const (
	TaskResultSuccess TaskResult = "success"
	TaskResultFailed  TaskResult = "failed"
)

func (e *TaskResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskResult(s)
	case string:
		*e = TaskResult(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskResult: %T", src)
	}
	return nil
}

type NullTaskResult struct {
	TaskResult TaskResult
	Valid      bool // Valid is true if TaskResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskResult) Scan(value interface{}) error {
	if value == nil {
		ns.TaskResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskResult), nil
}

type Climb struct {
	ID         int32
	UserID     int32
	ExternalID string
	ClimbDayID int32
	Grade      int32
	Color      string
	HoldColor  string
	ClimbType  ClimbType
	FinishType FinishType
}

type ClimbDay struct {
	ID         int32
	UserID     int32
	ExternalID string
	GymID      int32
	Day        pgtype.Timestamptz
}

type ClimbGym struct {
	ID         int32
	UserID     int32
	ExternalID string
	Name       string
	IconPath   string
}

type Exercise struct {
	ID        int32
	UserID    int32
	Name      string
	DeletedAt pgtype.Timestamptz
}

type ExercisesView struct {
	ID        pgtype.Int4
	UserID    pgtype.Int4
	Name      pgtype.Text
	DeletedAt pgtype.Timestamptz
}

type Session struct {
	ID        int32
	UserID    int32
	Name      string
	DeletedAt pgtype.Timestamptz
}

type SessionExercise struct {
	ID         int32
	SessionID  int32
	ExerciseID int32
	VariantID  pgtype.Int4
	Position   int32
	Sets       int32
	Reps       pgtype.Int4
	Weight     pgtype.Int4
	DurationS  pgtype.Int4
}

type SessionExercisesView struct {
	ID         pgtype.Int4
	SessionID  pgtype.Int4
	ExerciseID pgtype.Int4
	VariantID  pgtype.Int4
	Position   pgtype.Int4
	Sets       pgtype.Int4
	Reps       pgtype.Int4
	Weight     pgtype.Int4
	DurationS  pgtype.Int4
}

type Setting struct {
	ID                         int32
	UserID                     int32
	ClimbToploggerUserID       pgtype.Text
	ClimbToploggerAuthToken    pgtype.Text
	ClimbToploggerRefreshToken pgtype.Text
}

type Task struct {
	Uid       string
	Name      string
	Active    bool
	Recurring bool
}

type TaskRun struct {
	ID       int32
	TaskUid  string
	UserID   int32
	RunAt    pgtype.Timestamptz
	Result   TaskResult
	Error    pgtype.Text
	Duration int64
	Message  pgtype.Text
}

type User struct {
	ID   int32
	Uid  string
	Name string
}

type Variant struct {
	ID         int32
	ExerciseID int32
	Variant    string
}

type VariantsView struct {
	ID         pgtype.Int4
	ExerciseID pgtype.Int4
	Variant    pgtype.Text
}
