// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Exercise struct {
	ID        int32
	UserID    int32
	Name      string
	Variants  []string
	DeletedAt pgtype.Timestamptz
}

type Session struct {
	ID        int32
	UserID    int32
	Name      string
	Active    bool
	Position  pgtype.Int4
	DeletedAt pgtype.Timestamptz
}

type SessionsExercise struct {
	ID         int32
	SessionID  int32
	ExerciseID int32
	Variant    pgtype.Text
	Position   int32
	Sets       int32
	Reps       pgtype.Int4
	Weight     pgtype.Int4
	DurationS  pgtype.Int4
}

type User struct {
	ID   int32
	Uid  string
	Name string
}
