// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Exercise struct {
	ID        int32
	UserID    int32
	Name      string
	DeletedAt pgtype.Timestamptz
}

type ExercisesView struct {
	ID        pgtype.Int4
	UserID    pgtype.Int4
	Name      pgtype.Text
	DeletedAt pgtype.Timestamptz
}

type Session struct {
	ID        int32
	UserID    int32
	Name      string
	DeletedAt pgtype.Timestamptz
}

type SessionExercise struct {
	ID         int32
	SessionID  int32
	ExerciseID int32
	VariantID  pgtype.Int4
	Position   int32
	Sets       int32
	Reps       pgtype.Int4
	Weight     pgtype.Int4
	DurationS  pgtype.Int4
}

type SessionExercisesView struct {
	ID         pgtype.Int4
	SessionID  pgtype.Int4
	ExerciseID pgtype.Int4
	VariantID  pgtype.Int4
	Position   pgtype.Int4
	Sets       pgtype.Int4
	Reps       pgtype.Int4
	Weight     pgtype.Int4
	DurationS  pgtype.Int4
}

type User struct {
	ID   int32
	Uid  string
	Name string
}

type Variant struct {
	ID         int32
	ExerciseID int32
	Variant    string
}

type VariantsView struct {
	ID         pgtype.Int4
	ExerciseID pgtype.Int4
	Variant    pgtype.Text
}
