// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_exercise.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const sessionExerciseCreate = `-- name: SessionExerciseCreate :one
INSERT INTO session_exercises (session_id, exercise_id, variant_id, position, sets, reps, weight, duration_s)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type SessionExerciseCreateParams struct {
	SessionID  int32
	ExerciseID int32
	VariantID  pgtype.Int4
	Position   int32
	Sets       int32
	Reps       pgtype.Int4
	Weight     pgtype.Int4
	DurationS  pgtype.Int4
}

func (q *Queries) SessionExerciseCreate(ctx context.Context, arg SessionExerciseCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, sessionExerciseCreate,
		arg.SessionID,
		arg.ExerciseID,
		arg.VariantID,
		arg.Position,
		arg.Sets,
		arg.Reps,
		arg.Weight,
		arg.DurationS,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const sessionExerciseDelete = `-- name: SessionExerciseDelete :exec
DELETE FROM session_exercises
WHERE id = $1
`

func (q *Queries) SessionExerciseDelete(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, sessionExerciseDelete, id)
	return err
}

const sessionExerciseDeleteBySession = `-- name: SessionExerciseDeleteBySession :exec
DELETE FROM session_exercises
WHERE session_id = $1
`

func (q *Queries) SessionExerciseDeleteBySession(ctx context.Context, sessionID int32) error {
	_, err := q.db.Exec(ctx, sessionExerciseDeleteBySession, sessionID)
	return err
}

const sessionExerciseGetBySession = `-- name: SessionExerciseGetBySession :many
SELECT id, session_id, exercise_id, variant_id, position, sets, reps, weight, duration_s
FROM session_exercises
WHERE session_id = $1
ORDER BY position
`

func (q *Queries) SessionExerciseGetBySession(ctx context.Context, sessionID int32) ([]SessionExercise, error) {
	rows, err := q.db.Query(ctx, sessionExerciseGetBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionExercise
	for rows.Next() {
		var i SessionExercise
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ExerciseID,
			&i.VariantID,
			&i.Position,
			&i.Sets,
			&i.Reps,
			&i.Weight,
			&i.DurationS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
