// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const sessionCreate = `-- name: SessionCreate :one
INSERT INTO sessions (user_id, name, active, position)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type SessionCreateParams struct {
	UserID   int32
	Name     string
	Active   bool
	Position pgtype.Int4
}

func (q *Queries) SessionCreate(ctx context.Context, arg SessionCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, sessionCreate,
		arg.UserID,
		arg.Name,
		arg.Active,
		arg.Position,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const sessionDelete = `-- name: SessionDelete :exec
UPDATE sessions
SET deleted_at = NOW()
WHERE id = $1 AND NOT DELETED
`

func (q *Queries) SessionDelete(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, sessionDelete, id)
	return err
}

const sessionGet = `-- name: SessionGet :one
SELECT id, user_id, name, active, position, deleted_at
FROM sessions
WHERE id = $1
`

func (q *Queries) SessionGet(ctx context.Context, id int32) (Session, error) {
	row := q.db.QueryRow(ctx, sessionGet, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Active,
		&i.Position,
		&i.DeletedAt,
	)
	return i, err
}

const sessionGetAll = `-- name: SessionGetAll :many
SELECT id, user_id, name, active, position, deleted_at
FROM sessions
WHERE user_id = $1 AND NOT DELETED
ORDER BY name
`

func (q *Queries) SessionGetAll(ctx context.Context, userID int32) ([]Session, error) {
	rows, err := q.db.Query(ctx, sessionGetAll, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Active,
			&i.Position,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionUpdate = `-- name: SessionUpdate :exec
UPDATE sessions
SET name = $2, active = $3, position = $4
WHERE id = $1
`

type SessionUpdateParams struct {
	ID       int32
	Name     string
	Active   bool
	Position pgtype.Int4
}

func (q *Queries) SessionUpdate(ctx context.Context, arg SessionUpdateParams) error {
	_, err := q.db.Exec(ctx, sessionUpdate,
		arg.ID,
		arg.Name,
		arg.Active,
		arg.Position,
	)
	return err
}
