// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setting.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const settingCreate = `-- name: SettingCreate :one
INSERT INTO settings (user_id)
VALUES ($1)
RETURNING id
`

func (q *Queries) SettingCreate(ctx context.Context, userID int32) (int32, error) {
	row := q.db.QueryRow(ctx, settingCreate, userID)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const settingGetByUser = `-- name: SettingGetByUser :one
SELECT id, user_id, climb_toplogger_user_id, climb_toplogger_auth_token, climb_toplogger_refresh_token, climb_toplogger_expiration
FROM settings
WHERE user_id = $1
`

func (q *Queries) SettingGetByUser(ctx context.Context, userID int32) (Setting, error) {
	row := q.db.QueryRow(ctx, settingGetByUser, userID)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClimbToploggerUserID,
		&i.ClimbToploggerAuthToken,
		&i.ClimbToploggerRefreshToken,
		&i.ClimbToploggerExpiration,
	)
	return i, err
}

const settingToploggerUpdate = `-- name: SettingToploggerUpdate :exec
UPDATE settings
SET climb_toplogger_user_id = $2, climb_toplogger_auth_token = $3, climb_toplogger_refresh_token = $4, climb_toplogger_expiration = $5
WHERE id = $1
`

type SettingToploggerUpdateParams struct {
	ID                         int32
	ClimbToploggerUserID       pgtype.Text
	ClimbToploggerAuthToken    pgtype.Text
	ClimbToploggerRefreshToken pgtype.Text
	ClimbToploggerExpiration   pgtype.Timestamptz
}

func (q *Queries) SettingToploggerUpdate(ctx context.Context, arg SettingToploggerUpdateParams) error {
	_, err := q.db.Exec(ctx, settingToploggerUpdate,
		arg.ID,
		arg.ClimbToploggerUserID,
		arg.ClimbToploggerAuthToken,
		arg.ClimbToploggerRefreshToken,
		arg.ClimbToploggerExpiration,
	)
	return err
}
