// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlc

import (
	"context"
)

const userCreate = `-- name: UserCreate :one
INSERT INTO users (uid, name)
VALUES ($1, $2)
RETURNING id
`

type UserCreateParams struct {
	Uid  string
	Name string
}

func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, userCreate, arg.Uid, arg.Name)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const userGet = `-- name: UserGet :one
SELECT id, uid, name
FROM users
WHERE id = $1
`

func (q *Queries) UserGet(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, userGet, id)
	var i User
	err := row.Scan(&i.ID, &i.Uid, &i.Name)
	return i, err
}

const userGetAll = `-- name: UserGetAll :many
SELECT id, uid, name
FROM users
`

func (q *Queries) UserGetAll(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, userGetAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Uid, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userGetByUID = `-- name: UserGetByUID :one
SELECT id, uid, name
FROM users
WHERE uid = $1
`

func (q *Queries) UserGetByUID(ctx context.Context, uid string) (User, error) {
	row := q.db.QueryRow(ctx, userGetByUID, uid)
	var i User
	err := row.Scan(&i.ID, &i.Uid, &i.Name)
	return i, err
}
