// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: variant.sql

package sqlc

import (
	"context"
)

const variantCreate = `-- name: VariantCreate :one
INSERT INTO variants (exercise_id, variant)
VALUES ($1, $2)
RETURNING id
`

type VariantCreateParams struct {
	ExerciseID int32
	Variant    string
}

func (q *Queries) VariantCreate(ctx context.Context, arg VariantCreateParams) (int32, error) {
	row := q.db.QueryRow(ctx, variantCreate, arg.ExerciseID, arg.Variant)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const variantDelete = `-- name: VariantDelete :exec
DELETE FROM variants
WHERE id = $1
`

func (q *Queries) VariantDelete(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, variantDelete, id)
	return err
}

const variantDeleteByExercise = `-- name: VariantDeleteByExercise :exec
DELETE FROM variants
WHERE exercise_id = $1
`

func (q *Queries) VariantDeleteByExercise(ctx context.Context, exerciseID int32) error {
	_, err := q.db.Exec(ctx, variantDeleteByExercise, exerciseID)
	return err
}

const variantGet = `-- name: VariantGet :one
SELECT id, exercise_id, variant
FROM variants
WHERE id = $1
`

func (q *Queries) VariantGet(ctx context.Context, id int32) (Variant, error) {
	row := q.db.QueryRow(ctx, variantGet, id)
	var i Variant
	err := row.Scan(&i.ID, &i.ExerciseID, &i.Variant)
	return i, err
}

const variantGetByExercise = `-- name: VariantGetByExercise :many
SELECT id, exercise_id, variant
FROM variants
WHERE exercise_id = $1
`

func (q *Queries) VariantGetByExercise(ctx context.Context, exerciseID int32) ([]Variant, error) {
	rows, err := q.db.Query(ctx, variantGetByExercise, exerciseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Variant
	for rows.Next() {
		var i Variant
		if err := rows.Scan(&i.ID, &i.ExerciseID, &i.Variant); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const variantGetByIDs = `-- name: VariantGetByIDs :many
SELECT id, exercise_id, variant
FROM variants
WHERE id = ANY($1::int[])
`

func (q *Queries) VariantGetByIDs(ctx context.Context, dollar_1 []int32) ([]Variant, error) {
	rows, err := q.db.Query(ctx, variantGetByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Variant
	for rows.Next() {
		var i Variant
		if err := rows.Scan(&i.ID, &i.ExerciseID, &i.Variant); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const variantUpdate = `-- name: VariantUpdate :exec
UPDATE variants
SET variant = $2
WHERE id = $1
`

type VariantUpdateParams struct {
	ID      int32
	Variant string
}

func (q *Queries) VariantUpdate(ctx context.Context, arg VariantUpdateParams) error {
	_, err := q.db.Exec(ctx, variantUpdate, arg.ID, arg.Variant)
	return err
}
