app:
  name: "beta-log"

server:
  host: "0.0.0.0"
  port: 3000

auth:
  oidc:
    client_id: ""
    client_secret: ""
    callback_url: ""
    discovery_url: ""
  redirect_url: "/"

logger:
  file: "logs/backend.txt"
  level: "warn"

db:
  host: "db"
  port: 5432
  user: "postgres"
  password: "postgres"
  database: "postgres"

climb:
  interval_s: 3600
